### ISSUE TITLE
Proposal: osdev-gh web site

### ISSUE THREAD

**Issue by lcabrini** [osdev-gh/osdev-gh-doc#4]
I am going to suggest that we build a web site for the project and that we have list of all members, what they have worked on and a copy of all documents we have created. Nonetheless, image galleries and that kind of stuff as well as logs from all our meetings, whether physical or virtual.

There are a few reasons for why I am proposing this but the primary is that, if we are able to do something cool with our team, you would be able to have a reference on the website what you have done for the team. You can put the URL on your CV/resume and hopefully that should be able to kick of a career or two.

If we agree that this is a good idea, then we ask @Prince-linux to create osdev-gh-www as a project for the team and we can then discuss exactly what goes into the site, what framework to use and all other issues relating to this project in its own issue tracker.

**Comment by lcabrini** [comment]
@Prince-linux could you please label this with "proposal" or something like that?

**Comment by CollinsLord** [comment]
I would also like to contribute  to the web site project 
@Prince-linux kindly assign me to this project

**Comment by lcabrini** [comment]
@Prince-linux if we get enough interest in this, kindly set up osdev-gh-www to be the repository for the osdev-gh official web site. Then we move further discussion regarding the website to that projects issue tracker

**Comment by rexfordnyrk** [comment]
@Prince-linux I am interested in this. Kindly sign me up as well

**Comment by lcabrini** [comment]
Ok, we are getting some interest here. Cool. @Prince-linux what do you say, can we set up the repository for the project?

**Comment by Prince-linux** [comment]
Yes pls we can 
Cos I am also interested

**Comment by lcabrini** [comment]
OK, let's take a vote then. Who thinks we need a team web site and should set up the osdev-gh-www project?

**Comment by lcabrini** [comment]
Here is my +1

**Comment by laudb** [comment]
+1 yeah, I agree, I have some different ideas on this but open for discussion on its respective issue tracker

**Comment by lcabrini** [comment]
@laudb yes, if we agree then lets get the project started. Those who will be involved can then discuss exactly what goes on the site and how to develop it.

**Comment by lcabrini** [comment]
@CollinsLord , @rexfordnyrk please add your +1s so that we know that you have voted for. We have two +1s now, I think a few more and we have agreed.

**Comment by kelvinklufio** [comment]
+1. I do agree, let's do this!

**Comment by rexfordnyrk** [comment]
+1

**Comment by Prince-linux** [comment]
+1

**Comment by lcabrini** [comment]
ok @Prince-linux I think that's enough. Please set up osdev-gh-www repository. @laudb it's coming your way, would you like to get involved?

**Comment by CollinsLord** [comment]
Am in

**Comment by CollinsLord** [comment]
+1

**Comment by lcabrini** [comment]
Good, the project has been set up, so please let's go to that issue tracker and continue any discussion there.

@Prince-linux I propose we close this issue. What are your thoughts?

**Comment by Prince-linux** [comment]
very true

**Comment by kelvinklufio** [comment]
Do we have more than majority of the people on this platform to go ahead and close this issue? If so, then I second it fully.

**Comment by lcabrini** [comment]
@kelvinklufio I don't even think have agreed on how many members are required to vote on something. I see six votes and I think that should be fine.

**Comment by CollinsLord** [comment]
So what is the next move

**Comment by lcabrini** [comment]
@CollinsLord now go to the issue tracker for osdev-gh-www and start looking at issues there or add your own issues.
